Change styling of UI and code
rc-dining-bot/telegram-bot pull request #11
Opened 2020-02-11 17:05 UTC by moziliar

2020-02-12 14:01 UTC, jonchan51 requested changes
I think one thing we can add are default keyboard buttons for breakfast and dinner for today. so that the user doesn't need to type, can just press the button immediately. If they want other days then need to type

2020-02-12 14:01 UTC, jonchan51 commented on src/util/const.py
> +    f'{SET_BREAKFAST_NOTIFICATION_DESC}' \
Should we remove this first since we're not implementing?

2020-02-12 14:01 UTC, jonchan51 commented on src/util/kb_mark_up.py
> +    # (optionally) header/footer buttons
mention that it should be an array

2020-02-12 14:01 UTC, jonchan51 commented on src/util/messages.py
> +    return '<b>You do not have any hidden cuisine.</b>'
```suggestion
    return '<b>You do not have any hidden cuisines.</b>'
```

2020-02-12 15:55 UTC, moziliar commented on src/util/const.py
> +    f'{SET_BREAKFAST_NOTIFICATION_DESC}' \
Yes

2020-02-12 15:55 UTC, moziliar commented on src/util/kb_mark_up.py
> +    # (optionally) header/footer buttons
ok

2020-02-12 16:00 UTC, moziliar commented
> I think one thing we can add are default keyboard buttons for breakfast and dinner for today. so that the user doesn't need to type, can just press the button immediately. If they want other days then need to type

I think the links there are useful still. Can review the current UI and see if we should have the buttons instead? Could replace the /bfast /dinner with buttons but not sure if that'd enhance readability.

2020-02-13 03:46 UTC, jonchan51 approved these changes

2020-02-13 03:47 UTC, merged